name: build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and run tests
          run: |
            npm install
            npm run
